name: Hello_EC2_Here

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: ${{ secrets.TARGET_DIR }}

      - name: Execute .sh file on EC2
        run: |
          ssh -i ${{secrets.EC2_SSH_KEY}} ${{secrets.USERNAME}}@${{secrets.HOST_DNS}}





//////////////////////

name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Deploy Application to EC2
        run: |
          # Replace 'your-ec2-ip' and 'your-ec2-key.pem' with your EC2 instance details
          ssh -o StrictHostKeyChecking=no -i path/to/your/private/key.pem ec2-user@your-ec2-ip 'bash -s' << 'ENDSSH'
            # Navigate to your application directory
            cd /path/to/your/application

            # Pull the latest changes from the repository
            git pull origin main

            # Install Python dependencies
            pip install -r requirements.txt

            # Run your Python application
            python app.py
          ENDSSH

