name: EC2 Command Execution

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 STAGING
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build & Deploy
        env:
         SSH_PRIVATE_KEY: ${ { secrets.EC2_SSH_KEY }}
         REMOTE_HOST: ${ { secrets.HOST_DNS }}
         REMOTE_USER: ${ { secrets.USERNAME }}
         TARGET: ${ { secrets.TARGET_DIR }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key && chmod 600 private_key
          echo "this is: $REMOTE_USER"
      

