
name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: your-region

      - name: Deploy Application to EC2
        run: |
          # Replace 'your-ec2-ip' and 'your-ec2-key.pem' with your EC2 instance details
          ssh -o StrictHostKeyChecking=no -i practice_KP.pem  ec2-16-171-63-67.eu-north-1.compute.amazonaws.com 'bash -s' << 'ENDSSH'
            

          # Pull the latest changes from the repository
          git pull origin main

          # Run your Python application
          python app.py
          ENDSSH

